version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v5t9f2i2
      - REPOSITORY_URI=public.ecr.aws/v5t9f2i2/go-u2u
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-40)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - docker pull $REPOSITORY_URI:latest || true
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - export DOCKER_CLI_EXPERIMENTAL=enabled
      - mkdir -p ~/.docker/cli-plugins/
      - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.11.2/buildx-v0.11.2.linux-arm64" > ~/.docker/cli-plugins/docker-buildx
      - chmod a+x ~/.docker/cli-plugins/docker-buildx
      #- docker run --privileged --rm public.ecr.aws/v5t9f2i2/go-u2u:binfmt --install all
      - docker buildx create --use --name build --node build
      - echo "$REPOSITORY_URI:$IMAGE_TAG"
      #- docker buildx build --cache-from $REPOSITORY_URI:latest --platform linux/arm64 --tag $REPOSITORY_URI:$IMAGE_TAG -f Dockerfile.arm . --push
      #- make TAG=$IMAGE_TAG NET=mainnet u2u-image
      - curl -O https://raw.githubusercontent.com/unicornultrafoundation/u2u-genesis/main/mainnet.g
      - docker buildx build --platform linux/arm64,linux/amd64 --tag $REPOSITORY_URI:$IMAGE_TAG -f ./docker/Dockerfile.u2u --push
  post_build:
    commands:
      - echo Build completed on `date`