FROM golang:1.20-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git

WORKDIR /go/go-u2u
COPY . .

ARG GOPROXY
RUN go mod download
RUN make u2u



FROM alpine:latest

RUN apk add --no-cache ca-certificates

COPY --from=builder /go/go-u2u/build/u2u /

EXPOSE 5050 18545 18546 18547 19090

ENTRYPOINT ["/u2u"]
